-- MySQL:


-- CREATE TABLE `ci_sessions` (
--     `id` varchar(40) NOT NULL,
--     `ip_address` varchar(45) NOT NULL,
--     `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
--     `data` blob NOT NULL,
--     KEY `ci_sessions_timestamp` (`timestamp`)
--   ) ENGINE=InnoDB DEFAULT CHARSET=latin1;




INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AN18',  '1', '1', 'cod1',  'codigoI1',  1, 1, 1, 2, 'true', 'C:\BONOS.xlsx',     'Hoja1', 'true', 1.2525,   1, '30-10-2017', 100, 107.46, 1750, 100000, '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AA19',  '1', '1', 'Cod2',  'CodIsin2',  1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AA19',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AO20',  '1', '1', 'Cod3',  'CodIsin3',  1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AO20',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AA21',  '1', '1', 'Cod4',  'CodIsin4',  1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AA21',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AY24',  '1', '1', 'Cod5',  'CodIsin5',  1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AY24',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('A2E2',  '1', '1', 'Cod6',  'CodIsin6',  1, 1, 1, 2, 'true', 'BONOS.xlsm',        'A2E2',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('A2E3',  '1', '1', 'Cod7',  'CodIsin7',  1, 1, 1, 2, 'true', 'BONOS.xlsm',        'A2E3',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AA25',  '1', '1', 'Cod8',  'CodIsin8',  1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AA25',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AA26',  '1', '1', 'Cod9',  'CodIsin9',  1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AA26',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('A2E7',  '1', '1', 'Cod10', 'CodIsin10', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'A2E7',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('A2E8',  '1', '1', 'Cod11', 'CodIsin11', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'A2E8',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AL28',  '1', '1', 'Cod12', 'CodIsin12', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AL28',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('DICA',  '1', '1', 'Cod13', 'CodIsin13', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'DICA',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('DICY',  '1', '1', 'Cod14', 'CodIsin14', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'DICY',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AA37',  '1', '1', 'Cod15', 'CodIsin15', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AA37',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AL36',  '1', '1', 'Cod16', 'CodIsin16', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AL36',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PARA',  '1', '1', 'Cod17', 'CodIsin17', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'PARA',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PARY',  '1', '1', 'Cod18', 'CodIsin18', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'PARY',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AA46',  '1', '1', 'Cod19', 'CodIsin19', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AA46',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AE48',  '1', '1', 'Cod20', 'CodIsin20', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AE48',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AC17',  '1', '1', 'Cod21', 'CodIsin21', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AC17',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AE22',  '1', '1', 'Cod22', 'CodIsin22', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AE22',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AE23',  '1', '1', 'Cod23', 'CodIsin23', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AE23',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('DICE',  '1', '1', 'Cod24', 'CodIsin24', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'DICE',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AE27',  '1', '1', 'Cod25', 'CodIsin25', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AE27',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AE28',  '1', '1', 'Cod26', 'CodIsin26', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AE28',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PARE',  '1', '1', 'Cod27', 'CodIsin27', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'PARE',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AN47',  '1', '1', 'Cod28', 'CodIsin28', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AN47',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AMX9',  '1', '1', 'Cod29', 'CodIsin29', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AMX9',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AM20',  '1', '1', 'Cod30', 'CodIsin30', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AM20',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PR15',  '1', '1', 'Cod31', 'CodIsin31', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'PR15',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AA22',  '1', '1', 'Cod32', 'CodIsin32', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AA22',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('TC20',  '1', '1', 'Cod33', 'CodIsin33', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'TC20',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PR13',  '1', '1', 'Cod34', 'CodIsin34', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'PR13',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('TC21',  '1', '1', 'Cod35', 'CodIsin35', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'TC21',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('TC23',  '1', '1', 'Cod36', 'CodIsin36', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'TC23',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('DICP',  '1', '1', 'Cod37', 'CodIsin37', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'DICP',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PARP',  '1', '1', 'Cod38', 'CodIsin38', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'PARP',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('CUAP',  '1', '1', 'Cod39', 'CodIsin39', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'CUAP',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('TS18',  '1', '1', 'Cod40', 'CodIsin40', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'TS18',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('TO21',  '1', '1', 'Cod41', 'CodIsin41', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'TO21',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('TO23',  '1', '1', 'Cod42', 'CodIsin42', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'TO23',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('TO26',  '1', '1', 'Cod43', 'CodIsin43', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'TO26',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('AF19',  '1', '1', 'Cod44', 'CodIsin44', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'AF19',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('A2M2',  '1', '1', 'Cod45', 'CodIsin45', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'A2M2',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('TJ20',  '1', '1', 'Cod46', 'CodIsin46', 1, 1, 1, 2, 'true', 'BONOS.xlsm',        'TJ20',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PBD19', '2', '2', 'Cod47', 'CodIsin47', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PBD19', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PMJ21', '2', '2', 'Cod49', 'CodIsin49', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PMJ21', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BDC22', '2', '2', 'Cod50', 'CodIsin50', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BDC22', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PBY22', '2', '2', 'Cod52', 'CodIsin52', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PBY22', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BDC24', '2', '2', 'Cod53', 'CodIsin53', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BDC24', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PBA25', '2', '2', 'Cod54', 'CodIsin54', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PBA25', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BDC28', '2', '2', 'Cod55', 'CodIsin55', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BDC28', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('NDG21', '2', '2', 'Cod56', 'CodIsin56', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'NDG21', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PUO19', '2', '2', 'Cod57', 'CodIsin57', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PUO19', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BDC19', '2', '2', 'Cod58', 'CodIsin58', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BDC19', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BD2C9', '2', '2', 'Cod59', 'CodIsin59', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BD2C9', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BDC20', '2', '2', 'Cod60', 'CodIsin60', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BDC20', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PUM21', '2', '2', 'Cod61', 'CodIsin61', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PUM21', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PMO18', '2', '2', 'Cod62', 'CodIsin62', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PMO18', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PMD18', '2', '2', 'Cod63', 'CodIsin63', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PMD18', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BP18',  '2', '2', 'Cod64', 'CodIsin64', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BP18',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BPMD ', '2', '2', 'Cod65', 'CodIsin65', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BPMD ', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PBJ19', '2', '2', 'Cod66', 'CodIsin66', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PBJ19', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BP21',  '2', '2', 'Cod67', 'CodIsin67', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BP21',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PBJ21', '2', '2', 'Cod68', 'CodIsin68', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PBJ21', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('CO21D', '2', '2', 'Cod69', 'CodIsin69', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'CO21D', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PBF23', '2', '2', 'Cod70', 'CodIsin70', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PBF23', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PBM24', '2', '2', 'Cod71', 'CodIsin71', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PBM24', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('CO26',  '2', '2', 'Cod72', 'CodIsin72', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'CO26',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PMY24', '2', '2', 'Cod73', 'CodIsin73', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PMY24', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('SA24D', '2', '2', 'Cod74', 'CodIsin74', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'SA24D', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('RIF25', '2', '2', 'Cod75', 'CodIsin75', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'RIF25', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PUL26', '2', '2', 'Cod76', 'CodIsin76', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PUL26', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('ERF25', '2', '2', 'Cod77', 'CodIsin77', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'ERF25', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('NDT11', '2', '2', 'Cod78', 'CodIsin78', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'NDT11', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('RND25', '2', '2', 'Cod79', 'CodIsin79', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'RND25', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BP28',  '2', '2', 'Cod80', 'CodIsin80', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BP28',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('PBJ27', '2', '2', 'Cod81', 'CodIsin81', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'PBJ27', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('CO27D', '2', '2', 'Cod82', 'CodIsin82', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'CO27D', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('BPLD',  '2', '2', 'Cod83', 'CodIsin83', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'BPLD',  'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('RN20',  '2', '2', 'Cod84', 'CodIsin84', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'RN20 ', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');
INSERT INTO bono (nombre, emisor_id, tipobono_id, codigocaja, codigoisin, monedacobro_id, monedabono_id, tipotasa_id, tipotasavariable_id, cer, libro, hoja, actualizacionAutomatica, cupon, cantidadcuponanual, vencimiento, capitalresidual, ultimoprecio, oustanding, denominacionminima, proximointeres, proximoamortizacion, legislacion_id, fechaActualizacion) VALUES ('SA21',  '2', '2', 'Cod85', 'CodIsin85', 1, 1, 1, 2, 'true', 'provinciales.xlsm', 'SA21 ', 'true',    '0', '0', '30-10-2017', '0',    '0',  '0',    '0', '30-10-2017', '30-10-2017', 1, '30-10-2017');








-- CREATE TABLE calculadora.bonos (
--   id   int(11) unsigned NOT NULL AUTO_INCREMENT,
--   nombre varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   codigocaja varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   codigoisin double DEFAULT NULL,
--   monedacobro double DEFAULT NULL,
--   monedabono double DEFAULT NULL,
--   tipotasa varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   tipotasavariable varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   cer varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   cupon double DEFAULT NULL,
--   cantidadcuponanual int(11) unsigned DEFAULT NULL,
--   vencimiento varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   capitalresidual int(11) unsigned DEFAULT NULL,
--   ultimoprecio double DEFAULT NULL,
--   outstanding int(11) unsigned DEFAULT NULL,
--   proximointeres varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   proximoamortizacion varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   legislacion varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   denominacionminima int(11) unsigned DEFAULT NULL,
--   libro varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   hoja varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   emisor_id int(11) unsigned DEFAULT NULL,
--   tipobono_id int(11) unsigned DEFAULT NULL,
--   actualizacionAutomática int(11) unsigned DEFAULT NULL,
--   PRIMARY KEY (id)
--   KEY index_foreignkey_bono_emisor (emisor_id),
--   KEY index_foreignkey_bono_tipobono (tipobono_id),
--   CONSTRAINT cons_fk_bono_emisor_id_id FOREIGN KEY (emisor_id) REFERENCES emisor (id) ON DELETE SET NULL ON UPDATE SET NULL,
--   CONSTRAINT cons_fk_bono_tipobono_id_id FOREIGN KEY (tipobono_id) REFERENCES tipobono (id) ON DELETE SET NULL ON UPDATE SET NULL
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci


-- CREATE TABLE `bono` (
--   `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
--   `nombre` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `codigocaja` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `codigoisin` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `monedacobro` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `monedabono` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `tipotasa` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `tipotasavariable` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `cer` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `cupon` double DEFAULT NULL,
--   `cantidadcuponanual` int(11) unsigned DEFAULT NULL,
--   `vencimiento` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `capitalresidual` int(11) unsigned DEFAULT NULL,
--   `ultimoprecio` double DEFAULT NULL,
--   `oustanding` int(11) unsigned DEFAULT NULL,
--   `proximointeres` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `proximoamortizacion` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `legislacion` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `denominacionminima` int(11) unsigned DEFAULT NULL,
--   `libro` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `hoja` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `emisor_id` int(11) unsigned DEFAULT NULL,
--   `tipobono_id` int(11) unsigned DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `index_foreignkey_bono_emisor` (`emisor_id`),
--   KEY `index_foreignkey_bono_tipobono` (`tipobono_id`),
--   CONSTRAINT `cons_fk_bono_emisor_id_id` FOREIGN KEY (`emisor_id`) REFERENCES `emisor` (`id`) ON DELETE SET NULL ON UPDATE SET NULL,
--   CONSTRAINT `cons_fk_bono_tipobono_id_id` FOREIGN KEY (`tipobono_id`) REFERENCES `tipobono` (`id`) ON DELETE SET NULL ON UPDATE SET NULL
-- ) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci















-- emisor
-- 
-- feriados
-- 
-- flujo
-- 
-- moneda
-- 
-- tipobono
-- 
-- tipobono_id

-- CREATE TABLE calculadora.dato (
--   id   int(11) unsigned NOT NULL AUTO_INCREMENT,
--   bono varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   fecha varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   valorNominalActualizado double DEFAULT NULL,
--   valorResidualActualizado double DEFAULT NULL,
--   cuponAmortizacion double DEFAULT NULL,
--   cuponInteres varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   totalFlujo varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   fechaActualizacion date DEFAULT NULL,
--   
--   PRIMARY KEY (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ALTER TABLE calculadora.bono ADD COLUMN actualizacionAutomatica int(11);

